apiVersion: v1
kind: Secret
metadata:
  name: openstack_secret
type: opaque
stringData:
  admin: 
  masterKey: regopîherpohpomdkhreherh235423
  barbicanKey: t0p-Secret # required field for kubernetes.io/basic-auth
