apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/openstack-argocd-configs
    targetRevision: HEAD
    path: kind/applis
  helm:
    valueFiles:
      - openstack.yaml
    values: |
      appRoot: true
      targetRevision: dev
      apps:
        openstack:
          dnsSuffix: .kind.local
          masterKey: yoto
          barbican:
           key: totoroto
        openstack_users:
          admin: toto
          

      
  destination:
    name: in-cluster
    namespace: argocd