apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/openstack-argocd-configs
    targetRevision: HEAD
    path: kind/applis        
      
  destination:
    name: in-cluster
    namespace: argocd