configs:
  cm:
    statusbadge: enabled

  repositories:
    openstack-helm:
      url: https://github.com/openstack-argocd/openstack-helm-argocd.git
    openstack-helm-infra:
      url: https://github.com/openstack/openstack-helm-infra.git     
    openstack-argocd:
      url: https://github.com/openstack-argocd/openstack-argocd.git
    configs:
      url: https://github.com/openstack-argocd/configs.git   
      # istio-helm-repo:
    #   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
    #   name: istio.io
    #   type: helm
