apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: HEAD
    chart: argo/argo-cd
    helm:
      values: |
        server:
          ingress:
            ingressClassName: nginx
            enabled: true
        global:
          domain: argocd.kind.local
        configs:
          cm:
            url: https://argocd.kind.local
            statusbadge: enabled
            exec: enabled
        
          repositories:
            openstack-helm:
              url: https://github.com/openstack-argocd/openstack-helm-argocd.git
            openstack-helm-infra:
              url: https://github.com/openstack/openstack-helm-infra.git     
            openstack-argocd:
              url: https://github.com/openstack-argocd/openstack-argocd.git
            configs:
              url: https://github.com/openstack-argocd/configs.git           
            
          destination:
            server: https://kubernetes.default.svc
            namespace: argocd


